In [ ]:
from google.colab import auth
auth.authenticate_user()

from google.cloud import bigquery

client = bigquery.Client('scaler-sql-476312')

In [ ]:
query = """
SELECT *
FROM `scaler-sql-476312.farmers_market.product`
"""

df = client.query(query).to_dataframe()
df.head()

,product_id,product_name,product_size,product_category_id,product_qty_type
0,15,Red Potatoes - Small,,1,Null
1,1,Habanero Peppers - Organic,medium,1,lbs
2,2,Jalapeno Peppers - Organic,small,1,lbs
3,9,Sweet Potatoes,medium,1,lbs
4,13,Baby Salad Lettuce Mix,1 lb,1,lbs

# "*" means it will select all the rows and cols of the table

In [ ]:
query = """
SELECT *
FROM `scaler-sql-476312.farmers_market.customer`
"""

df = client.query(query).to_dataframe()
df.head()

   customer_id customer_first_name customer_last_name  customer_zip
0            1                Jane             Connor         22801
1            4              Deanna         Washington         22801
2            5             Abigail             Harris         22801
3            6               Betty            Bullard         22801
4            9               Janet             Forbes         22801

# If we need specific cols needs to display we need to mention the cols names in select Clause like **"select product_id,product_name"**

In [ ]:
query = """
SELECT product_id,product_name
FROM `scaler-sql-476312.farmers_market.product`
"""
df = client.query(query).to_dataframe()
df

    product_id                           product_name
0           15                   Red Potatoes - Small
1            1             Habanero Peppers - Organic
2            2             Jalapeno Peppers - Organic
3            9                         Sweet Potatoes
4           13                 Baby Salad Lettuce Mix
5           17                                Carrots
6           22                          Roma Tomatoes
7           14                           Red Potatoes
8            3              Poblano Peppers - Organic
9           12           Baby Salad Lettuce Mix - Bag
10          16                             Sweet Corn
11          18                      Carrots - Organic
12          21                Organic Cherry Tomatoes
13          23                      Maple Syrup - Jar
14           4                   Banana Peppers - Jar
15           5                      Whole Wheat Bread
16           7                              Apple Pie
17           8                             Cherry Pie
18           6                    Cut Zinnias Bouquet
19          11                             Pork Chops
20          10                                   Eggs
21          19  Farmer's Market Resuable Shopping Bag
22          20               Homemade Beeswax Candles

# **Using Orderby Clause**

**Orderby - ascending order**

In [ ]:
query = """
SELECT product_id,product_name
FROM `scaler-sql-476312.farmers_market.product`
ORDER BY product_id
"""
df = client.query(query).to_dataframe()
df

    product_id                           product_name
0            1             Habanero Peppers - Organic
1            2             Jalapeno Peppers - Organic
2            3              Poblano Peppers - Organic
3            4                   Banana Peppers - Jar
4            5                      Whole Wheat Bread
5            6                    Cut Zinnias Bouquet
6            7                              Apple Pie
7            8                             Cherry Pie
8            9                         Sweet Potatoes
9           10                                   Eggs
10          11                             Pork Chops
11          12           Baby Salad Lettuce Mix - Bag
12          13                 Baby Salad Lettuce Mix
13          14                           Red Potatoes
14          15                   Red Potatoes - Small
15          16                             Sweet Corn
16          17                                Carrots
17          18                      Carrots - Organic
18          19  Farmer's Market Resuable Shopping Bag
19          20               Homemade Beeswax Candles
20          21                Organic Cherry Tomatoes
21          22                          Roma Tomatoes
22          23                      Maple Syrup - Jar

**Orderby - descending order**

In [ ]:
query = """
SELECT product_id,product_name
FROM `scaler-sql-476312.farmers_market.product`
ORDER BY product_id DESC
"""
df = client.query(query).to_dataframe()
df

    product_id                           product_name
0           23                      Maple Syrup - Jar
1           22                          Roma Tomatoes
2           21                Organic Cherry Tomatoes
3           20               Homemade Beeswax Candles
4           19  Farmer's Market Resuable Shopping Bag
5           18                      Carrots - Organic
6           17                                Carrots
7           16                             Sweet Corn
8           15                   Red Potatoes - Small
9           14                           Red Potatoes
10          13                 Baby Salad Lettuce Mix
11          12           Baby Salad Lettuce Mix - Bag
12          11                             Pork Chops
13          10                                   Eggs
14           9                         Sweet Potatoes
15           8                             Cherry Pie
16           7                              Apple Pie
17           6                    Cut Zinnias Bouquet
18           5                      Whole Wheat Bread
19           4                   Banana Peppers - Jar
20           3              Poblano Peppers - Organic
21           2             Jalapeno Peppers - Organic
22           1             Habanero Peppers - Organic

**Both Ascending Order and Descending Order by using Order by Clause **

In [ ]:
query = """
SELECT product_id,product_name
FROM `scaler-sql-476312.farmers_market.product`
ORDER BY product_category_id DESC,product_id
"""
df = client.query(query).to_dataframe()
df

    product_id                           product_name
0           19  Farmer's Market Resuable Shopping Bag
1           20               Homemade Beeswax Candles
2           10                                   Eggs
3           11                             Pork Chops
4            6                    Cut Zinnias Bouquet
5            4                   Banana Peppers - Jar
6            5                      Whole Wheat Bread
7            7                              Apple Pie
8            8                             Cherry Pie
9           23                      Maple Syrup - Jar
10           1             Habanero Peppers - Organic
11           2             Jalapeno Peppers - Organic
12           3              Poblano Peppers - Organic
13           9                         Sweet Potatoes
14          12           Baby Salad Lettuce Mix - Bag
15          13                 Baby Salad Lettuce Mix
16          14                           Red Potatoes
17          15                   Red Potatoes - Small
18          16                             Sweet Corn
19          17                                Carrots
20          18                      Carrots - Organic
21          21                Organic Cherry Tomatoes
22          22                          Roma Tomatoes

# By Using Limit Clause

In [ ]:
query = """
SELECT *
FROM `scaler-sql-476312.farmers_market.customer_purchases`
ORDER BY market_date DESC, transaction_time DESC
LIMIT 10;
"""
df = client.query(query).to_dataframe()
df

,product_id,vendor_id,market_date,customer_id,quantity,cost_to_customer_per_qty,transaction_time
0,1,7,2020-09-30,18,2.26,6.99,18:58:00
1,1,7,2020-09-30,9,3.82,6.99,18:53:00
2,2,7,2020-09-30,19,3.36,3.49,18:53:00
3,3,7,2020-09-30,15,2.00,0.50,18:49:00
4,1,7,2020-09-30,9,3.61,6.99,18:49:00
5,2,7,2020-09-30,1,2.45,3.49,18:36:00
6,2,7,2020-09-30,9,2.93,3.49,18:33:00
7,1,7,2020-09-30,14,0.10,6.99,18:32:00
8,3,7,2020-09-30,1,3.00,0.50,18:18:00
9,3,7,2020-09-30,1,4.00,0.50,18:10:00

# **NOTE - Without using Limit we cannot use OFFSET Clause **

# OFFSET Clause

In [ ]:
query = """
SELECT *
FROM `scaler-sql-476312.farmers_market.customer_purchases`
ORDER BY market_date DESC, transaction_time DESC
LIMIT
  2 OFFSET 1;
"""
df = client.query(query).to_dataframe()
df

,product_id,vendor_id,market_date,customer_id,quantity,cost_to_customer_per_qty,transaction_time
0,2,7,2020-09-30,19,3.36,3.49,18:53:00
1,1,7,2020-09-30,9,3.82,6.99,18:53:00

# **Using Alias **

In [ ]:
query = """
SELECT *, cost_to_customer_per_qty * quantity AS Revenue
FROM `scaler-sql-476312.farmers_market.customer_purchases`;
"""
df = client.query(query).to_dataframe()
df

,product_id,vendor_id,market_date,customer_id,quantity,cost_to_customer_per_qty,transaction_time,Revenue
0,1,7,2019-07-03,14,0.99,6.99,17:32:00,6.9201
1,1,7,2019-07-03,14,2.18,6.99,18:23:00,15.2382
2,1,7,2019-07-03,15,1.53,6.99,18:41:00,10.6947
3,1,7,2019-07-03,16,2.02,6.99,18:18:00,14.1198
4,1,7,2019-07-03,22,0.66,6.99,17:34:00,4.6134
...,...,...,...,...,...,...,...,...
998,4,7,2019-06-15,8,1.00,4.00,13:10:00,4.0000
999,4,7,2019-06-15,8,1.00,4.00,13:54:00,4.0000
1000,4,7,2019-06-15,9,5.00,4.00,08:37:00,20.0000
1001,4,7,2019-06-15,11,3.00,4.00,12:01:00,12.0000
1002,4,7,2019-06-15,11,1.00,4.00,12:39:00,4.0000

# Using round() Function

In [ ]:
query = """
SELECT *, round(cost_to_customer_per_qty * quantity,2) AS Revenue
FROM `scaler-sql-476312.farmers_market.customer_purchases`;
"""
df = client.query(query).to_dataframe()
df

,product_id,vendor_id,market_date,customer_id,quantity,cost_to_customer_per_qty,transaction_time,Revenue
0,1,7,2019-07-03,14,0.99,6.99,17:32:00,6.92
1,1,7,2019-07-03,14,2.18,6.99,18:23:00,15.24
2,1,7,2019-07-03,15,1.53,6.99,18:41:00,10.69
3,1,7,2019-07-03,16,2.02,6.99,18:18:00,14.12
4,1,7,2019-07-03,22,0.66,6.99,17:34:00,4.61
...,...,...,...,...,...,...,...,...
998,4,7,2019-06-15,8,1.00,4.00,13:10:00,4.00
999,4,7,2019-06-15,8,1.00,4.00,13:54:00,4.00
1000,4,7,2019-06-15,9,5.00,4.00,08:37:00,20.00
1001,4,7,2019-06-15,11,3.00,4.00,12:01:00,12.00
1002,4,7,2019-06-15,11,1.00,4.00,12:39:00,4.00